"""reservation_unique_partial_index

Revision ID: 444ec8426cc7
Revises: 82d79b2c8a86
Create Date: 2025-10-31 12:47:45.551417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444ec8426cc7'
down_revision: Union[str, Sequence[str], None] = '82d79b2c8a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uc_showtime_seat'), 'reservations', type_='unique')
    op.create_index('uc_showtime_seat', 'reservations', ['show_time_id', 'seat_id'], unique=True, postgresql_where=sa.text("status = 'HELD' OR status = 'CONFIRMED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uc_showtime_seat', table_name='reservations', postgresql_where=sa.text("status = 'HELD' OR status = 'CONFIRMED'"))
    op.create_unique_constraint(op.f('uc_showtime_seat'), 'reservations', ['show_time_id', 'seat_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
