"""showtime_flag_is_processed_for_complete

Revision ID: f239bb2dc41a
Revises: 656e33453537
Create Date: 2025-11-23 16:08:50.459545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f239bb2dc41a'
down_revision: Union[str, Sequence[str], None] = '656e33453537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showtimes', sa.Column('is_processed_for_completion', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showtimes', 'is_processed_for_completion')
    # ### end Alembic commands ###
